import {ContentShell,DecisionTable} from "../../content-shell";
import {VolumeCalculator} from "../../moving-tools";
import {inventoryItems} from "../../inventory-data";
export const metadata={title:"Estimate Your Moving Volume in Cubic Metres | IMC",description:"Calculate packed item volume, understand inventory estimates and prepare a useful item list for an international moving quotation."};
export default function Volume(){return <ContentShell path="/guides/estimating-moving-volume/" category="Volume guidance" title="Estimate your moving volume in cubic metres." intro="Cubic metres describe space, not weight or price. Start with an inventory, distinguish estimates from measurements, and have the shipment volume confirmed before booking." related={[{href:"/get-a-quote/",label:"Build your quote inventory"},{href:"/services/shared-container/",label:"Explore shared-container planning"},{href:"/international-moving-costs/",label:"See what else affects cost"}]}>
<section><h2>Measure a packed item</h2><p>Enter the outside dimensions in centimetres. For identical items, use the quantity field. The result is the combined rectangular volume of those items, without an extra allowance for packing or loading.</p><VolumeCalculator/></section>
<section><h2>Two ways to estimate</h2><p>Use standard item volumes for a starting inventory estimate or outside dimensions for measured item volume. Shipment assessment brings those figures together with packing and loading requirements.</p><DecisionTable caption="Choose the method that matches your information" headings={["Method","Use it when","What the result means"]} rows={[["Inventory estimate","You know the item type and quantity but have not measured it","A starting estimate using a standard volume per item"],["Measured dimensions","You can measure the packed outside length, width and height","The bounding volume of the measured items"],["Shipment assessment","The inventory and packing requirements are ready for review","A basis for confirming the proposed service and quotation"]]}/></section>
<section><h2>How the inventory estimates work</h2><p>Our quote form contains {inventoryItems.length} item types from the supplied IMC planning list. Each has one estimated volume in m³. Add the items you are taking and adjust the quantities; the total is the sum of each item’s volume multiplied by its quantity.</p><p>For example, ten small cartons at 0.05 m³ each and two bookcases at 0.80 m³ each give an estimated 2.10 m³. That calculation does not establish the actual dimensions of your bookcases or a shipping price.</p><p>Repeated item names in the planning list were merged. Where the source contained different estimates for the same name, the larger value was retained. These are planning estimates, not guaranteed upper limits. If an item differs substantially from the description, explain it in your enquiry notes.</p></section>
<section><h2>Avoid double counting</h2><p>Maintain one working inventory and count each belonging once. Separate optional items from the confirmed shipment.</p><ul><li>Count each item once, even if it is moved between rooms during preparation.</li><li>Use the quantity of identical cartons; measure different carton sizes separately.</li><li>Note whether furniture will travel assembled or dismantled.</li><li>Include belongings in garages, sheds and storage areas.</li><li>Identify items you have not decided to take as optional rather than silently including them in a final list.</li></ul></section>
<section><h2>What an item-volume total cannot tell you</h2><p>Irregular shapes, protective packing and loading arrangements can change the space required for the shipment. A total from rectangular dimensions does not model how every piece will fit into a container.</p><p>Volume also does not tell you an item’s weight, its acceptability for a particular service or the amount of work needed to move it through a doorway. Keep those questions with the inventory for assessment. The final plan should use the actual items, route and packing requirements.</p></section>

<section><h2>Volume is not the same as chargeable weight</h2><p>Cubic metres measure space. Kilograms and pounds measure mass. A density assumption can estimate one from the other, but it cannot replace an actual measurement or a tariff’s charging rules.</p><p>One cubic metre is approximately 35.315 cubic feet. If one stage is quoted in weight and another in volume, request both measured or assessed quantities and the agreed conversion basis. For air cargo, compare actual weight with dimensional weight using the <a href="/guides/air-freight-chargeable-weight/">chargeable-weight explainer and calculator</a>.</p><p>Where weighing records are used, gross weight minus tare weight gives a net difference. Ask what each weighing includes, particularly packing and crating materials; the label “net” alone does not define what is billable.</p></section>
</ContentShell>}
