import { ContentShell, DecisionTable } from "../content-shell";
export const metadata={title:"International Removal Services | IMC",description:"Understand IMC’s door-to-door removal scope, shipment options, packing, storage and the details to agree before booking."};
export default function Services(){return <ContentShell path="/services/" category="Services" title="International removal services, door to door." intro="IMC manages international household removals from collection through to destination delivery. Your moving plan brings the transport, preparation and handoffs together around your belongings and circumstances." related={[{href:"/how-it-works/",label:"Follow the moving process"},{href:"/international-moving-costs/",label:"Understand moving costs"},{href:"/guides/estimating-moving-volume/",label:"Estimate your shipment volume"}]}>
<section><h2>What does door-to-door include?</h2><p>Door-to-door describes the intended start and finish of your removal. The written quotation should still define the work at each end, the transport between them and any charges or services outside the price. Use the scope below to shape that discussion.</p><DecisionTable caption="Build your removal scope" headings={["Part of the move","What to establish","What you provide"]} rows={[["Assessment","How volume, access and packing needs will be assessed","An inventory, photographs where useful and both locations"],["Packing and collection","Who packs, dismantles, carries and loads each item","Fragile items, access restrictions and collection availability"],["Transport and coordination","Mode, handling stages and estimated schedule","Timing priorities and any flexibility"],["Destination arrangements","Clearance support, release, delivery access and receiving arrangements","Requested documents and your delivery availability"],["Optional work","Storage, crating, unpacking and other work to be priced separately","A clear list of the help you need"]]}/></section>
<section id="small-moves"><h2>Moving a few items or part of a household</h2><p>A smaller shipment still needs an end-to-end plan. List each piece of furniture and each carton, add quantities and flag anything not represented in the item list. Our quote form includes an inventory picker for furniture-only and boxes/luggage enquiries.</p><p>Per-item volumes provide a starting estimate. Packing, unusual dimensions and loading requirements can change the assessed shipment volume. A low volume alone does not determine the most suitable service: route availability, minimum charges and your dates also matter.</p><p><a href="/services/shared-container/">Explore shared-container planning</a> or <a href="/get-a-quote/">start with your item list</a>.</p></section>
<section><h2>Choosing how your belongings travel</h2><p><a href="/services/full-container/">A sole-use container</a> reserves the container for one shipment. A shared-container arrangement combines shipments. Discuss both against the same inventory and delivery requirements. Air freight can be considered where available for a suitable shipment; it needs a separate assessment of dimensions, weight and restrictions.</p></section>
<section><h2>Packing, storage and receiving your move</h2><p>Agree what you will pack yourself and what needs professional packing or a separate handling plan. Describe fragile, bulky or unusually shaped belongings before the quotation is finalised. Identify stairs, lifts, parking limits and the distance between the vehicle and your doorway at both ends.</p><p>If your destination home will not be ready, discuss storage before collection. Ask where the goods will be held, how storage is charged, whether access is available and what redelivery includes. Availability and the agreed service scope depend on the shipment.</p></section>
<section><h2>Plan the work before and after transport</h2><p>Agree <a href="/services/packing/">packing responsibilities</a> before collection, and discuss <a href="/services/storage/">storage and redelivery</a> if the two homes will not be ready at the same time. Use the <a href="/guides/international-moving-checklist/">moving checklist</a> to record the remaining questions.</p></section>
<section><h2>IMC’s management role</h2><p>Our focus is coordinating your removal. The plan should identify the parties responsible for collection, transport and delivery, with the communication route clear to you. Immigration, tax, housing and school-placement advice are separate matters and should not be assumed to form part of a household-removal quotation.</p></section>
</ContentShell>}
