import { ContentShell, DecisionTable } from '../../content-shell';
import { MoveChecklist } from '../../moving-tools';
import { PlanningVisual } from '../../planning-visual';
export const metadata={title:'International Moving Checklist | IMC',description:'Prepare an international move with a practical checklist covering inventory, quotations, packing, collection and arrival.'};
export default function Checklist(){return <ContentShell path="/guides/international-moving-checklist/" category="Moving checklist" title="Turn your move into a sequence of decisions." intro="Start with the route, belongings and timing, then work through quotation, preparation and receiving arrangements. This checklist follows moving milestones so you can adapt it to your circumstances without relying on a fixed countdown.">
<MoveChecklist/>
<section><h2>What should you establish before requesting quotes?</h2><p>Build a moving brief that another person can understand without guessing. Record what you know and flag open questions, especially the destination address, access and delivery window.</p><ul><li>Collection and destination locations, including any likely changes.</li><li>A room-by-room inventory, with quantities and photographs where useful.</li><li>Items needing preparation, special handling or an acceptance check.</li><li>Your collection window, personal travel dates and earliest receiving date.</li></ul><p>For a small shipment, use the item list in our <a href="/get-a-quote/">quote request form</a>. Treat its volume as an estimate to support assessment.</p></section>
<section><h2>What should you resolve before booking?</h2><p>Resolve the scope questions that could change the work or price. Use the same brief to <a href="/guides/comparing-international-moving-quotes/">compare quotations</a>, and keep clarifications in writing.</p><DecisionTable caption="Booking decisions and the record to retain" headings={['Decision','Question to answer','Keep this record']} rows={[
['Packing','Who prepares each part of the shipment?','Packing scope and responsibilities'],['Transport','Which arrangement and schedule assumptions apply?','Transport description and estimated milestones'],['Arrival','Is the home ready or is storage needed?','Receiving plan or storage scope'],['Conditions','How are changes and additional work handled?','Quotation, booking conditions and clarifications']]} /></section>
<section><h2>What should happen before collection?</h2><p>Check the inventory again after sorting your belongings. Set aside items travelling with you, identify what stays behind and confirm the packing and property-access arrangements.</p><p>Complete the document and item checks requested for your actual shipment. Requirements differ by destination and circumstance; use the relevant authorities and coordinator’s instructions rather than treating a general checklist as approval.</p><PlanningVisual kind="packing"/><p>Our <a href="/services/packing/">packing guidance</a> explains how preparation should connect to the collection inventory.</p></section>
<section><h2>What remains while the shipment is travelling?</h2><p>Keep your contact details and receiving arrangements current. Understand the next expected milestone and which dates still depend on transport, release or delivery availability.</p><p>If the home or access changes, tell the coordinator before the delivery appointment is arranged. Use the <a href="/guides/delivery-day/">delivery-day guide</a> to prepare the room plan, recipient and checks.</p></section>
</ContentShell>}
