import { ContentShell, DecisionTable } from '../../content-shell';
import { PlanningVisual } from '../../planning-visual';
export const metadata={title:'Preparing for International Removal Delivery Day | IMC',description:'Prepare receiving arrangements, home access, room placement, inventory checks and follow-up for your international removal delivery.'};
export default function Delivery(){return <ContentShell path="/guides/delivery-day/" category="Delivery day" title="Make the final handoff a prepared one." intro="Before delivery, confirm the appointment, property access, authorised recipient and work included at the home. On the day, use the inventory and agreed reporting procedure to record what arrives and any outstanding concerns." related={[{href:'/guides/international-moving-times/',label:'Understand release and delivery milestones'},{href:'/services/storage/',label:'Discuss storage if the home is not ready'},{href:'/how-it-works/',label:'Review the complete moving process'}]}>
<PlanningVisual kind="delivery"/>
<section><h2>What should be confirmed before the appointment?</h2><p>Give the coordinator the current address and access details before scheduling. Information that was uncertain at quotation stage should be updated when the property is known.</p><DecisionTable caption="Receiving details to confirm with your coordinator" headings={['Detail','What to provide','Why it matters']} rows={[
['Recipient','Who will attend and how they can be reached','The team needs a clear receiving contact'],['Vehicle access','Parking, approach, restrictions and carrying distance','Access affects the delivery arrangement'],['Inside the property','Stairs, lift arrangements and narrow passages','The team needs to understand the route into the home'],['Room placement','A simple room plan and item destinations','Instructions help keep placement organised'],['Included work','Unpacking, reassembly and material removal if agreed','Optional work should match the written scope']]} /></section>
<section><h2>How should you prepare the home?</h2><p>Prepare clear access and decide where large pieces should go before delivery begins. If an item may not fit its intended room or access route, raise the concern with the coordinator in advance.</p><ul><li>Identify rooms clearly, especially where names differ from the origin home.</li><li>Keep walkways available and discuss any building access arrangements.</li><li>Keep the inventory and relevant delivery instructions accessible.</li><li>Arrange for an appropriate recipient to give placement instructions and complete checks.</li></ul><p>If the property is not ready, discuss a revised delivery or <a href="/services/storage/">storage arrangement</a> before assuming the shipment can be held without additional work or charges.</p></section>
<section><h2>What should you check during delivery?</h2><p>Follow the agreed inventory-checking procedure and note discrepancies clearly. Ask how cartons, furniture and any separately recorded pieces will be reconciled with the collection record.</p><p>Record visible concerns factually, including which item is affected and what you observed. Ask how matters discovered during later unpacking must be reported and which contractual or policy requirements apply.</p></section>
<section><h2>What should be clear before the team leaves?</h2><p>Confirm the work completed, any items or tasks outstanding and the route for follow-up. Retain the delivery record and a copy of any concerns recorded through the agreed process.</p><p>Unpacking, reassembly and removal of packing materials should be checked against the booked service. If additional work is requested, establish how it will be arranged and charged.</p></section>

<section><h2>Keep three different records linked</h2><p>The shipment inventory, a valuation list and the delivery record serve different purposes. Use the same item references where possible so a question about one piece can be followed through the move.</p><DecisionTable caption="Which document answers which question?" headings={["Record","Purpose","What to check"]} rows={[["Shipment inventory","Identifies cartons and individual pieces","Item numbers, descriptions and recorded condition"],["Valuation list, if required for cover","Records values on the basis required by the chosen policy","Valuation method, submission deadline and accepted evidence"],["Delivery record","Records receipt and observations at delivery","Missing numbers, visible concerns, photographs and follow-up route"]]}/><p>Photograph valuable items and serial numbers before packing, then retain the records. At delivery, record observations accurately and ask about concerns found after unpacking. These steps support a clear record; they do not guarantee a claim outcome or replace policy deadlines.</p></section>
</ContentShell>}
