import {ContentShell,DecisionTable} from "../../content-shell";
export const metadata={title:"Sole-Use Container Moving | Full Container Load | IMC",description:"Assess sole-use container shipping for household removals, including loading, capacity, access and door-to-door quote scope."};
export default function Full(){return <ContentShell path="/services/full-container/" category="Full container" title="Sole-use container moving: full container load." intro="A sole-use container, often called full container load or FCL, is reserved for one shipment. It can be worth considering for a substantial household move, subject to an assessment of volume, access and the route." related={[{href:"/services/shared-container/",label:"Compare shared-container planning"},{href:"/how-it-works/",label:"Understand the moving stages"},{href:"/international-moving-costs/",label:"Check quotation scope"}]}>
<section><h2>Sole use does not mean every item will fit</h2><p>The item inventory is the starting point. A container’s internal capacity and the space a particular shipment can use are different measures. Furniture shape, protective packing, stacking and handling can affect the loading plan.</p><p>Do not choose a container solely from the number of bedrooms in your home. Describe what is actually moving, including garage contents, outdoor furniture and unusually large pieces. Have the proposed container and loading arrangements confirmed after assessment.</p></section>
<section><h2>Clarify loading and delivery access</h2><p>Container access needs to be checked at both residences. Where direct positioning is unsuitable, the quotation should explain the alternative handling arrangement.</p><DecisionTable caption="Questions before choosing a dedicated container" headings={["Decision","What to establish"]} rows={[["Capacity","How the surveyed inventory and packing needs support the proposed container choice"],["Origin access","Whether the container can be positioned at the residence or goods need another loading arrangement"],["Destination access","Whether delivery is from the container or requires transfer into a suitable vehicle"],["Schedule","Which collection, departure and delivery milestones are confirmed or estimated"],["Charges","Which handling, waiting, storage or access-related charges may apply"],["Packing","Who packs and loads, and how fragile or oversized items will be handled"]]}/></section>
<section><h2>What a dedicated container changes</h2><p>Your shipment does not need to share container space with another household. That does not remove every source of delay or guarantee a delivery date. Transport schedules, release requirements and destination receiving arrangements still need coordination.</p><p>Compare dedicated and shared-container options against the same inventory and door-to-door scope. A sole-use option may leave some space unused; a shared arrangement may introduce different timing considerations. Ask for the practical trade-offs for your move rather than a universal size cut-off.</p></section>
<section><h2>Before collection</h2><p>Confirm the final inventory, packing responsibilities, access plan and documents requested for the shipment. Discuss any proposed addition before collection; do not assume a vehicle or unusually large item can be added simply because there appears to be spare space.</p><p>Keep essentials and documents you need during travel separate. Confirm who will receive the goods at destination and whether storage needs to be arranged if your home is not ready. Review the protection terms alongside the service quotation.</p></section>

<section><h2>Direct loading or a warehouse transfer?</h2><p>The loading location changes the handling plan. Establish the route your belongings take from the house into the container before comparing quotations.</p><DecisionTable caption="Loading arrangements to compare at survey" headings={["Arrangement","Goods movement","Questions to resolve"]} rows={[["Container positioned at the home","Home → container","Vehicle approach, lawful standing space, loading time and any permits"],["Warehouse loading","Home → collection vehicle → warehouse → container","Additional handling, temporary holding, inventory checks and charges"],["Transfer at destination","Container → warehouse or delivery vehicle → home","Receiving access, transfer arrangements and delivery scope"]]}/><p>Sole use describes allocation of space. It should not be read as a guarantee that a container will never be opened, inspected or transferred. Confirm the seal-recording procedure and who communicates any changes.</p></section>
</ContentShell>}
