import {ContentShell,DecisionTable} from "../../content-shell";
export const metadata={title:"Shared Container International Moving | IMC",description:"Understand groupage, shared-container suitability, consolidation timing and the questions to ask before choosing a service."};
export default function Shared(){return <ContentShell path="/services/shared-container/" category="Shared container" title="Shared-container moving and groupage." intro="Shared-container moving can suit a shipment that does not need a dedicated container. The choice depends on the route, available service, shipment size and how flexible your dates are." related={[{href:"/services/full-container/",label:"Consider a sole-use container"},{href:"/international-moving-costs/",label:"Compare the complete cost"},{href:"/guides/estimating-moving-volume/",label:"Understand your volume"}]}>
<section><h2>What is groupage?</h2><p>Groupage brings separate customers’ shipments together in a container. Your belongings remain an identified shipment, with their own inventory and delivery arrangements. Ask how the proposed service handles collection, consolidation, international transport and destination delivery.</p><p>You may also see the term LCL, meaning less than container load. Descriptions vary between services: ask whether the quoted arrangement is a household-removal consolidation service or another freight arrangement, and what handling and delivery scope is included. The label alone does not describe the whole service.</p></section>
<section><h2>Assess the fit before comparing prices</h2><p>Shared-container suitability depends on volume, route availability, timing and delivery scope together. Resolve these questions against your own shipment before comparing totals.</p><DecisionTable caption="Shared-container decision check" headings={["Consideration","Useful question"]} rows={[["Shipment size","What volume basis and minimum charge apply to my inventory?"],["Route availability","Is this service available for my actual origin and destination?"],["Timing","What depends on consolidation, and which dates remain estimates?"],["Handling","Where will my goods be held and how are shipments identified?"],["Delivery","What destination handling and final delivery are included?"],["Changes","What happens if the inventory, volume or receiving date changes?"]]}/></section>
<section><h2>When a small move needs more information</h2><p>Five cartons and one large furniture item may need different packing and handling from six ordinary cartons, even when the estimated volumes look similar. Record the actual items, quantities and any unusual dimensions. Mention fragile pieces, stairs and restricted access.</p><p>There is no single volume boundary that makes groupage the right choice for every move. Compare a shipment-specific quotation with any relevant alternative. A lower transport figure may not be a lower door-to-door total once handling, storage and delivery are included.</p></section>
<section><h2>Build flexibility into the plan</h2><p>Ask how collection relates to the planned consolidation and departure. If certain belongings are needed immediately on arrival, identify them early rather than assuming every item can meet the same deadline. Keep essential personal items out of the shipment as appropriate.</p><p>Before accepting a quote, establish what happens if delivery is not possible when the goods are ready. Storage arrangements, receiving availability and access should be considered as part of the decision, not left until arrival.</p></section>

<section id="groupage-vs-lcl"><h2>Household groupage or general-freight LCL?</h2><p>LCL describes sharing container capacity; it does not, by itself, specify a household-removal service. Ask whether the proposed consolidation is organised for household goods or through a general-freight network. Terminology varies, so establish the actual handling chain.</p><DecisionTable caption="Three service arrangements: confirm the actual contract and route" headings={["Arrangement","How space is organised","What to establish"]} rows={[["Household-goods groupage","Separate household shipments combined in a shared container","Who consolidates, how inventories remain separate and who unloads at destination"],["General-freight LCL","A freight consolidator combines compatible consignments; other cargo may be commercial","Packing or pallet requirements, freight-station handling, charging units and final delivery"],["Sole-use container","The container is allocated to one shipment","Loading location, access, transport milestones and any transfer before delivery"]]}/><p>For example, <a href="https://www.maersk.com/transportation-services/ocean-transport/lcl">Maersk describes LCL as consolidation with other businesses’ cargo</a>. That does not establish how another provider’s household service operates, or imply a partnership with IMC.</p></section>
<section><h2>Five answers that should accompany the price</h2><p>Ask for the service arrangement in writing so you can compare the handling and billing behind each quote.</p><ol><li>Who physically loads the container, and where?</li><li>Who separates shipments at destination, and where?</li><li>Is billing by cubic metre, weight or a weight-or-measure tariff?</li><li>Are destination handling, clearance work and home delivery included?</li><li>What is the consolidation closing date, and what happens if departure changes?</li></ol><p>The closing date is the deadline for that consolidation; it is not necessarily the sailing date. A low ocean-freight line alone cannot answer these questions.</p></section>
</ContentShell>}
