import {ContentShell,DecisionTable} from "../../content-shell";
import {ChargeableWeightTool} from "../../chargeable-weight-tool";
export const metadata={title:"Air Freight Chargeable Weight for Household Goods | IMC",description:"Compare actual and volumetric weight with a worked carton example, adjustable divisor and clear limits for international moving."};
export default function AirWeight(){return <ContentShell path="/guides/air-freight-chargeable-weight/" category="Air freight planning" title="A light carton can have a higher chargeable weight." intro="Air freight commonly compares actual packed weight with volumetric weight and uses the higher figure for rating. Bulky belongings can therefore have a chargeable weight above their scale weight; confirm the tariff before comparing quotations." related={[{href:'/guides/estimating-moving-volume/',label:'Understand cubic metres'},{href:'/guides/comparing-international-moving-quotes/',label:'Check your quotation basis'},{href:'/guides/international-moving-times/',label:'Plan essentials and arrival'}]}>
<ChargeableWeightTool/>
<section><h2>What is the calculation telling you?</h2><p>The example carton measures 60 × 50 × 40 cm outside its packing: 120,000 cm³, or 0.12 m³. At an illustrative divisor of 6,000, its volumetric weight is 20 kg. If the packed carton actually weighs 8 kg, the higher comparison figure is 20 kg before any tariff adjustments.</p><DecisionTable caption="The same carton under three illustrative rating scenarios" headings={['Actual weight','Divisor','Volumetric weight','Higher comparison weight']} rows={[["8 kg","6,000 cm³/kg","20 kg","20 kg"],["8 kg","5,000 cm³/kg","24 kg","24 kg"],["28 kg","6,000 cm³/kg","20 kg","28 kg"]]}/><p>Changing the divisor changes the comparison. A heavier item can instead be rated on actual weight. Use the divisor in your written quotation rather than assuming every air or courier service uses the same one.</p><p><a href="https://aviationcargo.dhl.com/business-tools/volume-calculator">DHL Aviation explains the actual-versus-volumetric comparison</a>. The scenarios here illustrate the arithmetic; they are not carrier quotations.</p></section>
<section><h2>Which measurements belong in the quote?</h2><p>Measure the packed outside dimensions and include the packaging in the actual weight. Ask whether the carrier measures each piece individually and how it handles rounding, pallets, overhang or non-stackable pieces.</p><p>A smaller protective package can change the volume, but reducing protection to save space can create another problem. Agree a suitable packing method for the item before treating the estimate as final.</p></section>
<section><h2>When might air complement a sea shipment?</h2><p>Separate belongings by when you need them rather than assuming the whole home needs one transport method. Identify a small group of arrival essentials and compare the complete air service with carrying suitable items yourself.</p><p>If the move is split between consignments, coordinate the inventories and destination documentation before dispatch. Acceptance, customs arrangements and any relief eligibility require a destination-specific check. Batteries, liquids and other potentially restricted contents must be declared for assessment; this calculator does not determine whether an item can fly.</p></section>
<section><h2>What does the calculator leave out?</h2><p>A chargeable weight is not a door-to-door price. Packing, collection, handling, security, clearance work, destination delivery, minimum charges and other tariff conditions can affect the final quotation.</p><p>Ask for the actual weight, dimensions, divisor and charging scope together. For multiple packages, request the carrier’s calculation for the complete consignment rather than multiplying this single-carton example without checking the rating method.</p></section>
</ContentShell>}
