import { ContentShell, DecisionTable } from '../../content-shell';
import { QuoteScopeGraphic } from '../../quote-scope-graphic';
export const metadata={title:'How to Compare International Moving Quotes | IMC',description:'Compare international removal quotations using the same inventory, addresses, services, dates and treatment of additional charges.'};
export default function Compare(){return <ContentShell path="/guides/comparing-international-moving-quotes/" category="Quote comparison" title="Compare the work behind the quotation." intro="Two moving quotations are comparable only when you understand the shipment, services and assumptions behind each total. Start with the same inventory and addresses, then reconcile inclusions, separate charges and unconfirmed details." related={[{href:'/international-moving-costs/',label:'Explore the factors affecting moving costs'},{href:'/services/packing/',label:'Clarify packing responsibilities'},{href:'/get-a-quote/',label:'Prepare your quote request'}]}>
<QuoteScopeGraphic/>
<section><h2>What must be the same before you compare?</h2><p>Give each company the same current moving brief. If one quotation uses an earlier inventory or assumes different access, its total describes different work.</p><DecisionTable caption="A comparison record to keep beside each quotation" headings={['Comparison point','Record for each quote','Resolve before deciding']} rows={[
['Inventory and assessment','Inventory version, assessed volume or weight and method','Are garages, storage areas and later additions included?'],['Origin and destination','Locations, property access and known restrictions','Are stairs, parking and carrying distances understood?'],['Packing and preparation','Who packs, materials and furniture preparation','Which dismantling, crating or reassembly tasks are included?'],['Transport','Mode and shared or sole-use arrangements','What routing and scheduling assumptions apply?'],['Destination services','Handling, home delivery and optional work','Who handles the destination stage and what remains separately charged?'],['Dates and validity','Collection window, estimates and quote expiry','What changes require a revised quotation?']]} /></section>
<section><h2>How should you treat missing information?</h2><p>Mark an unanswered item as unconfirmed. A blank line or an omitted service is not evidence that the work is free or included.</p><p>Ask for written clarification of the service, the responsible party and the price or calculation basis. If an amount depends on circumstances that are not yet known, record that dependency alongside the quoted total.</p></section>
<section><h2>Why can a lower headline total be misleading?</h2><p>A smaller quoted scope can produce a lower initial total while leaving work to be priced separately. Compare what you will receive before drawing a conclusion from the headline figures.</p><DecisionTable caption="Illustrative scope comparison; these are not actual IMC offers" headings={['Work','Quotation A','Quotation B']} rows={[
['Packing','Listed as included','Owner packing assumed'],['Home delivery','Listed to the specified address','Delivery scope requires clarification'],['Storage','Not included; charging basis supplied','Not mentioned'],['Your next action','Check assumptions and applicable terms','Request the missing scope and charges']]} /><p>Neither example is automatically preferable. The decision depends on the services you need and the terms ultimately agreed.</p></section>
<section><h2>What should you have before booking?</h2><p>Keep the written scope, current inventory and agreed conditions together. Confirm how changes, payments, protection arrangements and questions during the move will be handled.</p><ul><li>A named company responsible for the booking and a clear contact route.</li><li>A record of included, excluded and conditional services.</li><li>The treatment of changes to inventory, access or dates.</li><li>Clarity on the applicable protection terms and how concerns are reported.</li></ul><p>Use the <a href="/how-it-works/">moving process</a> to check that the quotation describes the full journey you intend to book.</p></section>

<section><h2>Ask for the unit, the overrun rate and the exclusions</h2><p>A quotation needs a charging basis as well as a total. If the inventory changes, a volume or weight allowance is exceeded, or access differs from the assumption, establish how the revised amount is calculated.</p><DecisionTable caption="The billing questions to resolve before collection" headings={["Quote detail","Ask in writing","Why it changes the comparison"]} rows={[["Charging unit","Cubic metres, cubic feet, kilograms, pounds, container rate or weight-or-measure?","Different units cannot be compared without their measurement basis"],["Packing weight or volume","Does the figure include cartons, crating, pallets and other packaging?","Packaging can change the assessed quantity"],["Additional quantity","What rate, minimum or revised service applies if the shipment grows?","An extra cubic metre may not cost the average quoted rate"],["Destination exclusions","Which handling, inspection, storage, release and delivery charges remain separate?","The ocean-freight figure may omit work needed to reach the home"],["Property access","What triggers shuttle, long-carry, stairs, parking or waiting charges?","The same inventory can require different work at each property"]]}/><p>A useful request is: “Please confirm the assessed quantity, charging unit, additional-quantity rate and every excluded or conditional charge, including who invoices it.”</p></section>
</ContentShell>}
