import { SiteHeader, SiteBrand } from "./site-identity";
import { imcBrand } from "./brand-system";
import { PageStructuredData } from "./structured-data";
import { PolicyFooter } from "./policy-footer";
import { TopicVisual } from "./topic-visual";
import type { ReactNode } from "react";
import { ArrowUpRight } from "lucide-react";
export function ContentShell({path,title,intro,category,children,related=[],showCta=true}:{path:string;title:string;intro:string;category:string;children:ReactNode;related?:{href:string;label:string}[];showCta?:boolean}){
return <><PageStructuredData path={path} title={title} intro={intro}/><a className="skip-link" href="#main">Skip to content</a><SiteHeader/><main id="main" className="content-page"><div className="content-hero"><div className="container"><nav className="crumbs" aria-label="Breadcrumb"><a href="/">Home</a><span aria-hidden="true">/</span><span aria-current="page">{title}</span></nav><p className="eyebrow">{category}</p><h1>{title}</h1><p className="content-intro">{intro}</p><TopicVisual topic={category}/></div></div><div className="container content-body">{children}</div>{related.length>0&&<nav className="container content-related" aria-label="Related moving guidance"><h2>Your next useful step</h2><div>{related.map(link=><a href={link.href} key={link.href}>{link.label}<ArrowUpRight size={19}/></a>)}</div></nav>}{showCta&&<section className="content-cta container"><div><h2>Your international move, clearly managed.</h2><p>Start with your locations, timing and what you’re taking.</p></div><a className="header-cta" href="/get-a-quote/">{imcBrand.enquiryLabel}<ArrowUpRight size={18}/></a></section>}</main><footer className="site-footer"><div className="container footer-main"><SiteBrand footer/><p>{imcBrand.promise}</p><a href="/services/">Explore our services</a><a href="/site-map/">Sitemap</a></div><PolicyFooter/></footer></>}
export function DecisionTable({headings,rows,caption}:{headings:string[];rows:string[][];caption:string}){return <div className="decision-table" role="region" aria-label={caption} tabIndex={0}><table><caption>{caption}</caption><thead><tr>{headings.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=>j===0?<th key={j} scope="row">{cell}</th>:<td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
