import { TransportGraphic, ContainerGraphic, VolumeBars } from "./moving-graphics";
import { QuoteScopeGraphic } from "./quote-scope-graphic";
import { Table, TableHeader, TableBody, TableRow, TableHead, TableCell, TableCaption } from "@/components/ui/table";
import { VolumeCalculator, MoveChecklist } from "./moving-tools";
import { Box, Ship, Plane, Warehouse, ClipboardList, ShieldCheck } from "lucide-react";
const scope = [
 [Box,"Packing & inventory","Decide what travels, what stays and who packs it. A room-by-room inventory makes the shipment easier to assess. Flag fragile items, dismantling and any special handling early."],
 [Ship,"Transport & containers","Compare sea freight, shared-container and full-container options against your shipment size and timing. Availability and the right configuration depend on your route."],
 [ClipboardList,"Documents & clearance","Prepare the inventory and supporting documents required for your shipment. Customs and biosecurity requirements are specific to the destination and your circumstances."],
 [Warehouse,"Storage & delivery","If your belongings and your new home will not be ready at the same time, discuss storage, handling and redelivery as part of the plan."],
 [ShieldCheck,"Protection & responsibilities","Ask how your belongings are protected, what the terms exclude, who handles each stage and how to report any issue. Keep the agreed scope in writing."],
 [Plane,"Time-sensitive belongings","Identify anything you need sooner than the main shipment. Discuss whether a separate air shipment or carrying essentials with you is appropriate."],
] as const;
export function PillarNavigation(){return <nav className="pillar-nav" aria-label="Explore this page"><div className="container"><span>PLAN YOUR MOVE</span><a href="#survey">Survey & scope</a><a href="#process">Moving process</a><a href="#transport">Shipping options</a><a href="#moving-costs">Costs & quotes</a><a href="#volume">Volume calculator</a><a href="#preparation">Checklist</a><a href="#questions">Questions</a></div></nav>;}
export function ScopeSection(){return <section id="move-scope" className="pillar-section container" aria-labelledby="scope-title"><div className="pillar-heading"><p className="eyebrow">YOUR MOVE, AS A WHOLE</p><h2 id="scope-title">What does an international<br/><span>door-to-door move involve?</span></h2><p>A door-to-door removal connects collection at your current home with delivery at your new one. The useful question is what happens between those doors—and exactly which services your quotation includes.</p></div><div className="scope-grid">{scope.map(([Icon,title,text])=><article key={title}><Icon size={27} strokeWidth={1.5}/><h3>{title}</h3><p>{text}</p></article>)}</div><p className="scope-footnote">These are the main elements to discuss when planning your move. The agreed quotation determines the services, partners and responsibilities for your shipment.</p></section>;}
export function TransportSection(){return <section id="transport" className="pillar-section container" aria-labelledby="transport-title"><div className="pillar-heading"><p className="eyebrow">CHOOSE WITH THE TRADE-OFFS IN VIEW</p><h2 id="transport-title">Shared container, full container<br/><span>or air freight?</span></h2><p>Start with how much you are taking and when you need it. Compare the options together before deciding what fits your move.</p></div><TransportGraphic/><ContainerGraphic/><Table className="transport-table"><TableCaption>General planning comparison. Routing, rates, departure schedules and availability need shipment-specific confirmation.</TableCaption><TableHeader><TableRow><TableHead scope="col">Option</TableHead><TableHead scope="col">Worth discussing when</TableHead><TableHead scope="col">What to weigh up</TableHead><TableHead scope="col">Ask before deciding</TableHead></TableRow></TableHeader><TableBody>
<TableRow><TableHead scope="row">Shared container<span>Groupage / consolidated sea freight</span></TableHead><TableCell>You have a smaller shipment and can allow flexibility.</TableCell><TableCell>Your belongings share container space with other shipments. Consolidation and the departure schedule affect timing.</TableCell><TableCell>How is space charged, when is departure expected and what happens if consolidation takes longer?</TableCell></TableRow>
<TableRow><TableHead scope="row">Full container<span>FCL / dedicated container</span></TableHead><TableCell>You have a larger household shipment or want dedicated container space.</TableCell><TableCell>Assess the usable load and access arrangements. A dedicated container does not remove clearance or delivery dependencies.</TableCell><TableCell>Which container size and loading method suit the inventory and both properties?</TableCell></TableRow>
<TableRow><TableHead scope="row">Air freight<span>Time-sensitive shipment</span></TableHead><TableCell>You need selected belongings ahead of the main move.</TableCell><TableCell>Weight, dimensions, item restrictions and destination handling matter. Flight time alone is not door-to-door time.</TableCell><TableCell>What weight basis, item rules and complete delivery estimate apply?</TableCell></TableRow>
</TableBody></Table><div className="comparison-note"><strong>One move can have more than one shipment.</strong><p>For example, discuss sending essentials separately while furniture travels by sea. This is a planning option, not a promise of availability or a recommended split for every move.</p></div><p className="source-note">Air-freight pricing context: <a href="https://www.iata.org/en/publications/newsletters/iata-knowledge-hub/air-cargo-tariffs-and-rules-what-you-need-to-know/">IATA explains actual and volumetric weight</a>.</p></section>;}
export function CostsSection(){return <section id="moving-costs" className="costs-section" aria-labelledby="costs-title"><div className="container"><div className="pillar-heading"><p className="eyebrow">UNDERSTAND THE QUOTE</p><h2 id="costs-title">What affects international<br/>moving costs?</h2><p>Your route, shipment size and service scope shape the price. A useful quotation explains the assumptions as clearly as the total.</p></div><QuoteScopeGraphic/><div className="cost-factors">{[["01","Route & transport","Collection and delivery locations, transport mode and routing."],["02","Size & preparation","Packed volume, weight where relevant, packing and special handling."],["03","Access & handling","Stairs, lifts, parking, carry distances and vehicle access at both homes."],["04","Timing & arrival","Departure availability, storage needs and delivery arrangements."]].map(([n,title,text])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="quote-comparison"><div><h3>Compare like-for-like<br/>service scope.</h3><p>Two quotes can look similar while covering different work. Use the same inventory, addresses and dates when requesting them.</p></div><dl>{[["Included services","Packing materials, collection, freight, destination handling, delivery and any unpacking."],["Conditional or excluded costs","Ask about duties or taxes, examinations, storage, port-related charges and difficult access; establish which apply and who pays."],["Protection and changes","Check protection terms, valuation, excesses, exclusions, quote validity and how inventory or date changes are priced."]].map(([title,text])=><div key={title}><dt>{title}</dt><dd>{text}</dd></div>)}</dl></div></div></section>;}
export function VolumeSection(){return <section id="volume" className="pillar-section container" aria-labelledby="volume-title"><div className="pillar-heading"><p className="eyebrow">MAKE SHIPMENT SIZE TANGIBLE</p><h2 id="volume-title">How much space<br/><span>will your belongings take?</span></h2><p>Calculate the volume of a packed item or a set of identical cartons. This helps you understand cubic metres before a full inventory or survey.</p></div><VolumeCalculator/><VolumeBars/><div className="tool-context"><h3>From an item measurement to a moving survey</h3><p>Repeat the calculation for different items and add their volumes. A survey then considers the whole shipment: protective wrapping, furniture shape, dismantling, loading and items that cannot stack. Bedroom count alone is not a measured shipment volume.</p><p>Worked example: ten cartons measuring 50 × 40 × 40 cm occupy 0.8 m³ before any allowance for loading space. This tool calculates geometry; it does not calculate a removal price or select a container.</p></div></section>;}
export function PreparationSection(){return <section id="preparation" className="preparation-section" aria-labelledby="preparation-title"><div className="container"><div className="pillar-heading"><p className="eyebrow">LESS TO HOLD IN YOUR HEAD</p><h2 id="preparation-title">Your international moving checklist.</h2><p>Check the topics you have already worked through. We’ll highlight the next question to resolve so your conversation starts with the details that matter.</p></div><MoveChecklist/></div></section>;}
export function PracticalSection(){return <section className="pillar-section container" id="practical-details" aria-labelledby="practical-title"><div className="pillar-heading"><p className="eyebrow">THE DETAILS THAT CHANGE THE PLAN</p><h2 id="practical-title">Prepare for departure.<br/><span>Plan for arrival.</span></h2></div><div className="practical-grid"><article id="documents"><span className="topic-index">01 / DOCUMENTS</span><h3>Customs & biosecurity</h3><p>Use your destination’s current requirements to prepare the document set. Depending on the move, this may include identification, an inventory, shipping documents and evidence relevant to your residence or import status.</p><p>Check restricted items before packing. Do not assume household goods, food, plants, outdoor equipment or batteries can travel under the same rules everywhere.</p><a href="https://www.fidi.org/customs-guides">Consult FIDI’s country customs guides ↗</a><small>Industry reference, not a statement of IMC membership. Confirm current requirements with the relevant authority and your move coordinator.</small></article><article id="protection"><span className="topic-index">02 / PROTECTION</span><h3>Inventory, condition & cover</h3><p>Keep a clear inventory and record the condition of items before collection. Ask what protection is available and read the applicable policy or contractual terms.</p><p>Discuss valuation, exclusions, excesses, owner-packed items, storage periods and the process for notifying loss or damage. Do not assume a mover’s liability and separate transit insurance provide identical protection.</p><strong>Your useful question</strong><p>“What applies to my belongings during each stage, and what would I need to do if there were a problem?”</p></article><article id="delivery"><span className="topic-index">03 / ARRIVAL</span><h3>Timing, storage & home access</h3><p>A sailing or flight schedule covers only part of the move. Collection, preparation, consolidation where relevant, release and final delivery all need to fit into the plan.</p><p>If your new home is not ready, discuss storage location, handling, access, protection and redelivery costs. Confirm parking, stairs, lifts and who will receive the goods before delivery day.</p><strong>Your useful question</strong><p>“Which dates are estimates, what could change them and when will the next update be available?”</p></article></div></section>;}
const questions=[
 ["What does an international relocation management company do?","It coordinates the stages and parties involved in moving belongings between countries. IMC focuses on worldwide door-to-door removals. The written scope should identify what is managed, who performs each stage and what you need to provide."],
 ["Can IMC manage a move between two countries outside my home country?","IMC’s focus is worldwide door-to-door moves, rather than a single origin market. Share the actual collection and delivery locations so route feasibility and service requirements can be assessed."],
 ["What information do I need for an international moving quote?","Start with origin and destination, your collection window, a working inventory and any known access issues. Add packing, storage, fragile-item and timing requirements. A survey may be needed to establish the shipment scope."],
 ["Can I move just a few boxes or part of a household?","A smaller shipment needs its own assessment. Ask about available shared-container or other suitable options and compare minimum charges, handling and timing. Do not assume that a small volume automatically makes air freight or sea freight the better choice."],
 ["Can I pack my own belongings?","Discuss this before packing. Acceptance, packing standards and the treatment of owner-packed items under protection terms depend on the service and route. Keep an inventory and check any required inspection or repacking arrangements."],
 ["How long does an international move take?","There is no useful worldwide delivery time that fits every move. Ask for a route-specific estimate covering collection to delivery, including consolidation if relevant, clearance and receiving arrangements. Distinguish indicative dates from confirmed appointments."],
 ["Does door-to-door mean all charges are included?","No. Check the written inclusions and exclusions. Duties, inspections, storage or unusual access can require separate treatment depending on the agreement and circumstances."],
 ["Should I ship furniture or replace it after arrival?","Compare its usefulness, replacement cost and suitability for the new home against the incremental cost and practical demands of shipping it. Include sentimental value, dimensions, access and any electrical compatibility checks for appliances."],
];
export function QuestionsSection(){return <section id="questions" className="questions-section" aria-labelledby="questions-title"><div className="container"><div className="pillar-heading"><p className="eyebrow">CLEAR ANSWERS, BEFORE YOU ASK</p><h2 id="questions-title">International moving questions.</h2></div><dl className="question-grid">{questions.map(([q,a])=><div key={q}><dt>{q}</dt><dd>{a}</dd></div>)}</dl><div className="pillar-closing"><div><h2>Your next step starts<br/>with a clearer picture.</h2><p>Keep your route, inventory and timing together as you plan your move.</p></div><a className="header-cta" href="#enquiry">Back to your enquiry space ↑</a></div></div></section>;}
