import { MilestoneGraphic } from "./moving-graphics";
const process = [
 ["Define your move", "Establish the collection and delivery locations, your timing and the belongings you want to take.", "Share addresses or locations, a date window and any immediate questions.", "A starting brief with the main requirements and open questions."],
 ["Assess the shipment", "Build an inventory and assess volume, packing, handling and access. Agree how this assessment will be completed.", "Include storage areas, outdoor items and anything awkward or fragile.", "A recorded shipment scope and the assumptions behind it."],
 ["Review the quotation", "Compare the proposed transport, services, conditions and exclusions against your needs.", "Check who handles each stage and ask about any unclear or conditional charges.", "A written scope you can evaluate before making a booking decision."],
 ["Confirm arrangements", "Agree the booking terms, preparation requirements and dates that can be confirmed.", "Check the payment schedule, document requirements and what happens if plans change.", "A booking record and a list of actions before collection."],
 ["Prepare and collect", "Complete the agreed packing and collection arrangements, with inventory and condition records.", "Separate items staying behind, keep essentials with you and confirm access.", "A record of the belongings collected and any agreed exceptions."],
 ["Transport the shipment", "Coordinate the agreed route and the handoffs between origin, carrier and destination services.", "Keep contact details current and understand which dates remain estimates.", "Relevant transport information and the next expected milestone."],
 ["Prepare for release", "Resolve the destination document and release requirements that apply to your move.", "Provide requested information promptly and confirm how any additional requirements will be handled.", "Confirmation of release when available, followed by delivery arrangements."],
 ["Deliver and check", "Complete the agreed delivery, placement and any contracted unpacking or reassembly.", "Be available to receive the shipment, check the inventory and record concerns using the agreed procedure.", "A delivery record and clear follow-up for any outstanding items."],
];
export function DetailedProcess(){return <section id="process" className="detailed-process" aria-labelledby="process-title"><div className="container"><div className="pillar-heading"><p className="eyebrow">FROM THE FIRST CONVERSATION TO DELIVERY</p><h2 id="process-title">A clear plan at every stage.</h2><p>Use this sequence to understand the decisions and handoffs in a door-to-door removal. Your quotation and booking documents establish the arrangements for your move.</p></div><MilestoneGraphic/><ol className="process-detail-grid">{process.map(([title,description,action,outcome],i)=><li key={title}><span className="process-detail-number">0{i+1}</span><h3>{title}</h3><p>{description}</p><dl><div><dt>Your part</dt><dd>{action}</dd></div><div><dt>What to have clear</dt><dd>{outcome}</dd></div></dl></li>)}</ol><div className="process-takeaway"><strong>Keep the same plan through each handoff.</strong><p>Ask who your contact is, which updates to expect and who can resolve questions at origin and destination. A change to inventory, dates or access should be reflected in the agreed arrangements.</p></div></div></section>;}
export function SurveySection(){return <section className="pillar-section container" id="survey" aria-labelledby="survey-title"><div className="pillar-heading"><p className="eyebrow">START WITH THE RIGHT INFORMATION</p><h2 id="survey-title">What a pre-move assessment<br/><span>needs to establish.</span></h2><p>An assessment connects the belongings you want to move with the work required to move them. It should cover the inventory, packing requirements, property access and the points that could change the scope.</p></div><div className="survey-grid">{[
 ["An inventory-led assessment","Useful when you can describe and measure the shipment clearly.","List each room and storage area. Include quantities, dimensions where useful, photographs and items needing special handling. Flag anything you are undecided about."],
 ["A video walkthrough","Useful when the shipment needs a guided look across several spaces.","Prepare to show furniture, cupboards, garages and outdoor belongings, as well as stairs and the route to the collection vehicle. Keep measurements available for items that are difficult to judge on screen."],
 ["An in-person assessment","Worth discussing for complex access or a substantial shipment.","Make the relevant areas accessible and identify items needing dismantling, crating or additional protection. Discuss what will change between assessment and collection."],
 ].map(([title,intro,text])=><article key={title}><h3>{title}</h3><strong>{intro}</strong><p>{text}</p></article>)}</div><div className="survey-output"><div><h3>Leave the assessment with a clearer scope.</h3><p>Confirm which assessment methods are available for your location and move before arranging one.</p></div><ul><li>What is included in the inventory—and what is excluded.</li><li>How volume or weight has been assessed and which assumptions remain.</li><li>Who packs, dismantles and prepares each part of the shipment.</li><li>What access, timing or destination details still need confirmation.</li></ul></div></section>;}
export function PackingStorageSection(){return <section className="packing-storage-section" aria-labelledby="handling-title"><div className="container"><div className="pillar-heading"><p className="eyebrow">BEFORE THE JOURNEY. AFTER ARRIVAL.</p><h2 id="handling-title">Packing, storage and delivery<br/><span>deserve their own plan.</span></h2></div><div className="handling-grid"><article id="packing"><span className="topic-index">PACKING & PREPARATION</span><h3>Agree how each item will be prepared.</h3><p>Discuss whether full packing, selected-item packing or owner packing fits the shipment. The quotation should identify the work included, any materials supplied and the preparation you are responsible for.</p><ul><li><strong>Furniture:</strong> identify protective wrapping, dismantling and reassembly needs.</li><li><strong>Fragile or awkward items:</strong> flag unusual dimensions, delicate finishes and any need for bespoke protection.</li><li><strong>Cartons and inventories:</strong> establish labelling and recording arrangements so the shipment can be checked.</li><li><strong>Essentials:</strong> keep travel documents, keys and items you need immediately separate from the removal shipment.</li></ul><p>Before packing items yourself, confirm acceptance requirements and how owner-packed contents are treated under the applicable protection terms.</p></article><article id="storage"><span className="topic-index">STORAGE & FINAL DELIVERY</span><h3>Plan for the gap between two homes.</h3><p>If collection and delivery dates do not align, ask whether storage at origin or destination is appropriate. Establish its location, handling arrangements and how the goods will be released for onward delivery.</p><ul><li><strong>Dates and charges:</strong> clarify the charging period and the cost of handling and redelivery.</li><li><strong>Access:</strong> ask whether you can retrieve individual items and what notice or handling is involved.</li><li><strong>Protection:</strong> confirm what applies during the full storage period.</li><li><strong>Delivery scope:</strong> agree receiving arrangements, room placement and any unpacking, reassembly or packing-material removal.</li></ul><p>Give the delivery team the relevant access details before scheduling: stairs, lifts, parking restrictions and any limits on vehicle size.</p></article></div></div></section>;}
export function MoveSituations(){return <section className="pillar-section container move-situations" aria-labelledby="situations-title"><div className="pillar-heading"><p className="eyebrow">BUILD THE PLAN AROUND YOUR BELONGINGS</p><h2 id="situations-title">A household, a smaller shipment<br/><span>or a move in stages.</span></h2></div><div className="situation-grid">{[
 ["A complete household","Build the inventory room by room, including items in lofts, garages and gardens. Discuss the packing workload and receiving arrangements as well as transport.","Start with the survey","#survey"],
 ["Selected furniture and boxes","Confirm what is actually travelling. Compare the available shipment options, any minimum charges and how flexible your delivery window can be.","Compare transport options","#transport"],
 ["Belongings arriving separately","Separate what you need immediately from what can arrive later. Discuss separate shipments and any storage, without assuming they will follow the same schedule.","Plan storage and arrival","#storage"],
 ].map(([title,text,label,href])=><article key={title}><h3>{title}</h3><p>{text}</p><a href={href}>{label} →</a></article>)}</div></section>;}
