import { ContentShell, DecisionTable } from '../../content-shell';
import { MilestoneGraphic } from '../../moving-graphics';
export const metadata={title:'International Moving Times and Milestones | IMC',description:'Understand collection, departure, transit, arrival, release and delivery when planning the timing of an international move.'};
export default function Times(){return <ContentShell path="/guides/international-moving-times/" category="Moving times" title="A sailing date is not your delivery date." intro="An international moving estimate needs to cover the journey from collection to home delivery. Preparation, consolidation where applicable, transport, destination release and the final appointment are separate stages with their own dependencies." related={[{href:'/services/shared-container/',label:'Understand consolidation'},{href:'/services/storage/',label:'Plan a gap between homes'},{href:'/guides/delivery-day/',label:'Prepare for delivery'}]}>
<MilestoneGraphic/>
<section><h2>Which dates should you ask for?</h2><p>Ask what each date describes and whether it is an estimate or a confirmed appointment. A transport schedule provides only part of the information needed to plan when you can receive your belongings.</p><DecisionTable caption="Different milestones in a door-to-door moving estimate" headings={['Milestone','What it describes','What to clarify']} rows={[
['Collection','Goods leave the origin property','Packing days, access and collection appointment'],['Departure','The international transport stage begins','Consolidation or handling before dispatch'],['Arrival','The shipment reaches its arrival point','Destination work still required'],['Release','Applicable release requirements have been resolved','Any remaining steps before delivery can be booked'],['Home delivery','Goods arrive at the receiving property','Appointment, access, recipient and service scope']]} /></section>
<section><h2>What can change the schedule?</h2><p>A change at one stage can affect later arrangements. Ask which dependencies are relevant to your shipment and when the next useful update is expected.</p><ul><li>Changes to the inventory, preparation or collection access.</li><li>Consolidation and departure availability for a shared shipment.</li><li>Changes to the transport schedule or handling arrangements.</li><li>Outstanding destination information or release requirements.</li><li>A receiving property that is not ready or has different access.</li></ul><p>These are planning considerations, not a prediction that your shipment will experience each issue.</p></section>
<section><h2>How should you plan belongings needed earlier?</h2><p>Identify essentials before collection and discuss them separately from the main household shipment. Decide what you will carry and what may need another arrangement, subject to acceptance and availability.</p><p>A useful list says when each group is needed. “Work equipment needed on arrival” gives the coordinator more to assess than a general request for a fast move.</p></section>
<section><h2>What if the home is not ready?</h2><p>Discuss storage and redelivery before the shipment reaches the point where those decisions are urgent. Confirm where it could be held, how the period is charged and how a later appointment is arranged.</p><p>Keep your collection window, travel dates and receiving date separate in the moving brief. There is no single worldwide transit estimate that can accurately replace a route-specific assessment.</p></section>

<section><h2>Ask when each storage clock starts</h2><p>Free time and storage arrangements belong to a particular booking, facility and charge. Do not assume one allowance covers the port, container equipment, a consolidation warehouse and delivery scheduling.</p><DecisionTable caption="A timing record to obtain before departure" headings={["Record","Question","Planning consequence"]} rows={[["Start of the allowance","Which event starts the clock?","Arrival, availability and release may be different dates"],["End of the allowance","What is the last free day and how are days counted?","Weekends or holidays may affect the calculation"],["Charge after expiry","Who charges, at what rate, and are there other simultaneous charges?","A warehouse quote may not include every port or equipment charge"],["Receiving readiness","What documents, release conditions and access arrangements are outstanding?","A home delivery appointment depends on more than vessel arrival"]]}/><p>Compare origin storage, destination warehouse storage and other options using actual handling and redelivery costs. There is no universal cheapest location or worldwide free-time allowance.</p></section>
</ContentShell>}
