import { ContentShell, DecisionTable } from '../../content-shell';
import { PlanningVisual } from '../../planning-visual';
export const metadata={title:'Packing for International Removals | IMC',description:'Plan packing responsibilities, furniture preparation, fragile items and inventory records for your international removal.'};
export default function Packing(){return <ContentShell path="/services/packing/" category="Packing" title="Packing starts with knowing what is moving." intro="An international packing plan identifies the belongings travelling, the preparation each item needs and who will do the work. Discuss the scope before packing begins so the assessment, quotation and collection inventory stay aligned." related={[{href:'/guides/international-moving-checklist/',label:'Prepare your moving checklist'},{href:'/guides/estimating-moving-volume/',label:'Understand packed volume'},{href:'/services/storage/',label:'Plan any storage'}]}>
<PlanningVisual kind="packing"/>
<section><h2>Who will pack which belongings?</h2><p>Agree the packing responsibility item by item or room by room. Full packing, selected-item packing and owner packing involve different work; availability and acceptance need confirmation for your move.</p><DecisionTable headings={['Approach','What to establish','Your preparation']} rows={[
['Full packing','Which rooms, materials and furniture preparation the quote includes','Identify items staying behind, essential belongings and anything needing special attention'],['Selected-item packing','Exactly which pieces or categories the team will prepare','Keep your own packing list separate and record the division of work'],['Owner packing','Acceptance, labelling, inspection and any repacking requirements','Confirm standards before buying materials or sealing cartons']]} caption="Packing responsibilities to agree before collection"/><p>A packing description should also address dismantling, crating where required, and reassembly at destination. Do not assume that work at delivery is included because it was completed at origin.</p></section>
<section><h2>What needs attention during the assessment?</h2><p>Identify belongings that need more information than a standard item name can provide. Dimensions, photographs and a description of the condition help frame the discussion; the actual preparation method should be agreed with the team handling the item.</p><ul><li><strong>Furniture:</strong> dimensions, detachable parts, existing marks and narrow access points.</li><li><strong>Fragile pieces:</strong> delicate finishes, glass, unusual shapes and any existing packaging.</li><li><strong>Appliances and equipment:</strong> preparation instructions, detachable accessories and anything requiring specialist disconnection.</li><li><strong>Cartons:</strong> quantities, outside dimensions and a clear contents description.</li></ul><p>Describe items you may add later. An assessment of a partly packed room can become inaccurate if the inventory changes without being updated.</p></section>
<section><h2>How should packing connect to the inventory?</h2><p>Use a consistent record that lets a carton or furniture piece be matched to the shipment inventory. Ask how the collection team will label, count and record the goods and how you will receive a copy.</p><p>For planning volume, avoid counting a carton and its contents as separate packed items. A measured carton volume and a standard furniture estimate are different methods; our <a href="/guides/estimating-moving-volume/">volume guide</a> explains the distinction.</p></section>
<section><h2>What should stay separate on collection day?</h2><p>Set aside belongings you intend to carry yourself before the packing team begins. Clearly identify items that are not part of the shipment and check the relevant transport rules for anything you plan to carry.</p><ul><li>Travel documents, keys and the details needed to reach your coordinator.</li><li>Belongings needed before the shipment arrives.</li><li>Items awaiting an acceptance decision or further instructions.</li><li>Property belonging to a landlord or another household member.</li></ul><p>Keep any uncertain item out of the packing workflow until the appropriate requirements are confirmed. Destination and carrier restrictions need a shipment-specific check.</p></section>

<section><h2>What does ISPM 15 mean for a wooden crate?</h2><p>ISPM 15 addresses pest risks in raw-wood packaging used in international trade, including dunnage. The standard excludes qualifying processed-wood packaging such as plywood. A crate made with plywood panels may still contain solid-wood supports that need assessment.</p><p>Ask the packing provider to confirm the materials, applicable destination requirements and any required treatment and marking. A familiar-looking crate is not evidence of compliance. See the <a href="https://www.ippc.int/en/publications/640/">International Plant Protection Convention’s ISPM 15 guidance</a>.</p></section>
<section><h2>Prepare for moisture and inspection before packing</h2><p>Tell the packing team about damp items, outdoor equipment and belongings with soil or organic residue before they are wrapped. Confirm cleaning, drying and appliance preparation instructions rather than sealing uncertain items inside cartons.</p><ul><li>Drain and dry appliances according to their manufacturer’s instructions and the packer’s requirements.</li><li>Check bicycles, garden tools, camping equipment and outdoor furniture for residue.</li><li>Ask how sensitive finishes and moisture risks will influence packing materials.</li><li>Identify batteries, liquids and other potentially restricted goods for a carrier and destination check.</li></ul><p>Packing methods, acceptance and any protection cover need to be agreed for the item and journey. Owner packing does not have one universal insurance outcome; obtain the actual conditions before deciding who packs.</p></section>
</ContentShell>}
